### ISSUE TITLE
Upgrade babel-jest to ^9.0.0 or newer

### ISSUE THREAD

**Issue by lauterry** [justinsisley/Jest-CSS-Modules#1]
Hello @justinsisley 

Please upgrade babel-jest dependencies to ^9.0.0 or newer.

I got ```Unknow option: .babelrc.presets``` when running jest.

I have declared ```"babel-jest": "^9.0.0"``` in my devDependencies.

Best regards

**Comment by lauterry** [comment]
Thx @justinsisley 👍

**Comment by lauterry** [comment]
Could you publish a new version in npm with the updated package.json please ?

Thx a lot

**Comment by justinsisley** [comment]
Done!

**Comment by lauterry** [comment]
👍
