### ISSUE TITLE
TypeError: Jest: a transform must export a `process` function.

### ISSUE THREAD

**Issue by emily-ellevation** [justinsisley/Jest-CSS-Modules#21]
After installing the package and adding the transform, I'm getting a new error `TypeError: Jest: a transform must export a `process` function.` Not sure if this a breaking change introduced by a Jest upgrade? I ran using `--no-cache`

**package.json**
```
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "jest-css-modules": "^2.1.0",
     ...
  "jest": {
    "transform": {
	  "^.+\\.js$": "babel-jest",
	  "\\.(css|less|scss|sss|styl)$": "<rootDir>/node_modules/jest-css-modules"

    }
  }
```

**Comment by lemoustachiste** [comment]
any luck with this?

**Comment by emily-ellevation** [comment]
Abandoned ship and went with `jest-css-modules-transform`

**Comment by lemoustachiste** [comment]
I tried installing `identity-obj-proxy` as per the Readme documentation but the error persisted.
Installed `jest-css-modules`@v1.1 and worked out of the box.
