### ISSUE TITLE
Document usage of --no-cache after installing preprocessor.

### ISSUE THREAD

**Issue by jseminck** [justinsisley/Jest-CSS-Modules#4]
People will generally first already have executed jest tests on a broken file before coming here and finding this project. They will then install the preprocessor, run again, but the test still fails.

Why? According to jest docs, you need to use the `--no-cache` flag when working with script preprocessors on files that have already been processed before. See: https://facebook.github.io/jest/docs/api.html#scriptpreprocessor-string

I think it would be very useful to document this as well.

**Comment by justinsisley** [comment]
Please submit a PR to the readme and I'll review.

**Comment by justinsisley** [comment]
Closing, as this information has been added.
