### ISSUE TITLE
Regex expression is incorrect

### ISSUE THREAD

**Issue by jseminck** [justinsisley/Jest-CSS-Modules#5]
I'm no regex expert, so please correct me if I am wrong.

The current regex for me filtered out files names that ended in: `myTest.spec.js`. It was matching the `.s` part. I changed the regex to the following to make it work.

```js
if (filename.match(/.*\.\(css\|less|scss|styl\)/)) {
   return '';
}
```

**Comment by p-decoraid** [comment]
Confirming the issue - the regexp as found in npm package excludes any files containing a dot followed by c, s, l, e, t, y or l. In particular a file name like "foo.test.js" has a dot followed by t and would be excluded.

00339d7149a10a7efd3802a72b488e49338eba02 has the fix, please release a new version to npm.

**Comment by justinsisley** [comment]
Updated version and published to NPM.
