### ISSUE TITLE
Does not work with react-css-modules

### ISSUE THREAD

**Issue by p-decoraid** [justinsisley/Jest-CSS-Modules#9]
After fixing #5 locally I am getting:

<pre>
butler% npm test

> @ test /home/me/apps/frontend
> jest

 FAIL  library/paymentform.test.js
  ● paymentform › renders patterns without slashes

    "form-reactbuttons" CSS module is undefined.
      
      at exports.default (node_modules/react-css-modules/dist/generateAppendClassName.js:41:23)
      at linkElement (node_modules/react-css-modules/dist/linkClass.js:67:65)
      at node_modules/react-css-modules/dist/linkClass.js:59:24
      at mapSingleChildIntoContext (node_modules/react/lib/ReactChildren.js:108:26)
...
</pre>

... which seems to make sense given that jest-css-modules skips loading of the css modules.

Am I missing something to make jest-css-modules work with react-css-modules?

**Comment by p-decoraid** [comment]
I followed https://facebook.github.io/jest/docs/tutorial-webpack.html to address this issue, but now I am not clear on what the use case of jest-css-modules is today.

**Comment by justinsisley** [comment]
From the documentation you've referenced, it would appear that the following pattern is the best way forward, and you should no longer need this library.

```
{
  "jest": {
    "moduleNameMapper": {
      "^.+\\.(css|less)$": "identity-obj-proxy"
    }
  }
}
```

**Comment by justinsisley** [comment]
Obviously, you should modify the regex to suit your project's needs.
